// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Question struct {
	Title     string `json:"title"`
	InputType string `json:"inputType"`
	InputSpec string `json:"inputSpec"`
}

type QuestionInput struct {
	Title     string `json:"title"`
	InputType string `json:"inputType"`
	InputSpec string `json:"inputSpec"`
}

type Survey struct {
	ID        string      `json:"_id"`
	Title     string      `json:"title"`
	Token     string      `json:"token"`
	Questions []*Question `json:"questions"`
	IsDeleted bool        `json:"isDeleted"`
}

type SurveyInput struct {
	Title     string           `json:"title"`
	Token     string           `json:"token"`
	Questions []*QuestionInput `json:"questions"`
}
